From 3eb47d02fa07cf8884901c12d2a93c7c9fb12372 Mon Sep 17 00:00:00 2001
From: fabian4 <cybing4@gmail.com>
Date: Mon, 27 Jun 2016 18:49:50 +0800
Subject: [PATCH 2/4] Fix soft_delete,User has been deleted instance, The user
 quota have never changed. Redmine #7102 http://192.168.15.2/issues/7102

Signed-off-by: fabian <cybing4@gmail.com>
Signed-off-by: fabian4 <cybing4@gmail.com>
---
 nova/compute/api.py | 13 +++++++++----
 1 file changed, 9 insertions(+), 4 deletions(-)

diff --git a/nova/compute/api.py b/nova/compute/api.py
index 3eaa877..78b08b3 100644
--- a/nova/compute/api.py
+++ b/nova/compute/api.py
@@ -1774,10 +1774,15 @@ class API(base.Base):
         """Terminate an instance."""
         LOG.debug('Going to try to soft delete instance',
                   instance=instance)
-
-        self._delete(context, instance, 'soft_delete', self._do_soft_delete,
-                     task_state=task_states.SOFT_DELETING,
-                     deleted_at=timeutils.utcnow())
+        if instance['vm_state'] == vm_states.SOFT_DELETED:
+            LOG.warn("Instance %s is soft delete state" % (instance.uuid))
+            reason = ("The instance is %s state" % (instance.vm_state))
+            raise exception.InstanceTerminationFailure(reason=reason)
+        else:
+            self._delete(context, instance, 'soft_delete',
+                         self._do_soft_delete,
+                         task_state=task_states.SOFT_DELETING,
+                         deleted_at=timeutils.utcnow())
 
     def _delete_instance(self, context, instance):
         self._delete(context, instance, 'delete', self._do_delete,
-- 
2.1.0

